### PR TITLE
Sustitute paperclip-318.jar for paperlclip.jar

### PR DESCRIPTION
**Pull request by chusqui**
To correct the download in the installation of Paper

### CODE REVIEW

**Comment by colin1497** [comment]
Nice.  Do you know if this pulls latest build or latest stable or what?

**Comment by chusqui** [comment]
Sorry.
No idea. It is my first attempt yo do a pull request in my whole life. 
I think is based in the latest build.
Thank you for your effort

**Review by naesean — APPROVED** [review]
Can we please get the PR merged in? I can't install Paperclip because the version # is hard-coded.

**Comment by officeboy** [comment]
> Nice. Do you know if this pulls latest build or latest stable or what?

DOWNLOAD_PATH references the "lastSuccessfulBuild".  If you want the last stable build it should be getting paperclip.jar from https://papermc.io/ci/job/Paper-1.15/lastStableBuild/ 
Other options are
https://papermc.io/ci/job/Paper-1.15/lastBuild/
https://papermc.io/ci/job/Paper-1.15/lastCompletedBuild/
Also failed and unsuccessfull but lets not use those.

**Comment by colin1497** [comment]
> 
> 
> > Nice. Do you know if this pulls latest build or latest stable or what?
> 
> DOWNLOAD_PATH references the "lastSuccessfulBuild". If you want the last stable build it should be getting paperclip.jar from https://papermc.io/ci/job/Paper-1.15/lastStableBuild/
> Other options are
> https://papermc.io/ci/job/Paper-1.15/lastBuild/
> https://papermc.io/ci/job/Paper-1.15/lastCompletedBuild/
> Also failed and unsuccessfull but lets not use those.

Thanks, I hadn't gone digging far enough into Paper to find the stable build path, and we moved this summer and this has been way back on the backburner for me.  I'll check into this ASAP.

**Comment by colin1497** [comment]
Merged with update to 1.16 stable path.  Thank you @officeboy for the digging there.

Looking at the stable builds tag I don't know if there's a whole lot of validation that things are stable there, so hoping this won't break people down the road.

**Pull request closed without merging**
